// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsfmwihtyudknqnznefx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzZm13aWh0eXVka25xbnpuZWZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5MzMyMjEsImV4cCI6MjA1MDUwOTIyMX0.Gg7-el0hiGJ_n5gs7RmqaJ8v-UWAStqol23axYO59sg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);